OBJS	= .o
SOURCE	= .cpp
HEADER	= 
OUT	= PL.out
CC	 = g++
FLAGS	 = -g -c -Wall
LFLAGS	 = 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

.o: .cpp
	$(CC) $(FLAGS) .cpp 


clean:
	rm -f $(OBJS) $(OUT)
